definitions:
  config:
    /hippo:namespaces/myproject/product:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: fdf2bffc-b274-43ee-9e61-a3f38463c7c0
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 0d65f306-5506-43b2-b554-0af397b8e53b
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel', 'mix:referenceable']
          jcr:uuid: 90149127-2810-4f13-b180-c5f2902130f4
          hipposysedit:node: true
          hipposysedit:supertype: ['myproject:basedocument', 'hippostd:relaxed', 'hippotranslation:translated']
          hipposysedit:uri: http://www.onehippo.org/myproject/nt/1.0
          /title:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myproject:title
            hipposysedit:primary: false
            hipposysedit:type: String
            hipposysedit:validators: [non-empty, required]
          /introduction:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myproject:introduction
            hipposysedit:primary: false
            hipposysedit:type: Text
          /description:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myproject:description
            hipposysedit:primary: false
            hipposysedit:type: hippostd:html
          /price:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myproject:price
            hipposysedit:primary: false
            hipposysedit:type: Double
          /rating:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myproject:rating
            hipposysedit:primary: false
            hipposysedit:type: Double
          /instock:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: myproject:instock
            hipposysedit:primary: false
            hipposysedit:type: Long
          /categories:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: true
            hipposysedit:ordered: false
            hipposysedit:path: myproject:categories
            hipposysedit:primary: false
            hipposysedit:type: String
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: myproject:product
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: 980ccf1c-44b0-4022-8a33-218f7d5ecada
          hippo:related___pathreference: []
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:creationDate: 2015-08-03T14:34:09.332+02:00
          hippostdpubwf:lastModificationDate: 2015-08-03T14:34:09.332+02:00
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          myproject:categories: []
          myproject:instock: 0
          myproject:introduction: ''
          myproject:price: 0.0
          myproject:rating: 0.0
          myproject:title: ''
          /myproject:description:
            jcr:primaryType: hippostd:html
            hippostd:content: ''
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            extension.left: ${cluster.id}.left
            extension.right: ${cluster.id}.right
            plugin.class: org.hippoecm.frontend.editor.layout.TwoColumn
            wicket.extensions: [extension.left, extension.right]
          /left:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.left.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.left
          /right:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.right.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.right
          /title:
            jcr:primaryType: frontend:plugin
            caption: Title
            field: title
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /introduction:
            jcr:primaryType: frontend:plugin
            caption: Introduction
            field: introduction
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /description:
            jcr:primaryType: frontend:plugin
            caption: Description
            field: description
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /price:
            jcr:primaryType: frontend:plugin
            caption: Price
            field: price
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /rating:
            jcr:primaryType: frontend:plugin
            caption: Rating
            field: rating
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /instock:
            jcr:primaryType: frontend:plugin
            caption: '# In Stock'
            field: instock
            hint: ''
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /categories:
            jcr:primaryType: frontend:plugin
            caption: categories
            field: categories
            multiselect.type: selectlist
            palette.alloworder: false
            palette.maxrows: ''
            plugin.class: org.onehippo.forge.selection.frontend.plugin.DynamicMultiSelectPlugin
            selectlist.maxrows: ''
            valuelist.provider: service.valuelist.default
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              source: /content/documents/myproject/configuration/categories
