definitions:
  config:
    /hst:hst/hst:configurations:
      /common:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
        /hst:abstractpages:
          jcr:primaryType: hst:pages
        /hst:pages:
          jcr:primaryType: hst:pages
        /hst:components:
          jcr:primaryType: hst:components
        /hst:templates:
          jcr:primaryType: hst:templates
          /base-layout:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/myproject/base-layout.ftl
          /base-top-menu:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/myproject/base-top-menu.ftl
          /base-footer:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/myproject/base-footer.ftl
          /homepage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/myproject/homepage-main.ftl
          /pagenotfound-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/myproject/pagenotfound-main.ftl
          /newspage-main:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hstdefault/newspage-main.ftl
          /contentlist-main-contentlist:
            jcr:primaryType: hst:template
            hst:renderpath: webfile:/freemarker/hstdefault/contentlist-main-contentlist.ftl
        /hst:sitemenus:
          jcr:primaryType: hst:sitemenus
        /hst:catalog:
          jcr:primaryType: hst:catalog
          /myproject-catalog:
            jcr:primaryType: hst:containeritempackage
      /myproject:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
      /mijnproject:
        jcr:primaryType: hst:configuration
        hst:inheritsfrom: [../common]
