/hst:hst/hst:configurations/myproject/hst:workspace/hst:containers/productlist/main/productlist:
  jcr:primaryType: hst:containeritemcomponent
  hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsListComponent
  hst:iconpath: images/catalog-component-icons/product-list.png
  hst:label: Product List
  hst:parameternames: [path, documentTypes, sortOrder, sortField, pageSize, showPagination,
    includeSubtypes]
  hst:parametervalues: ['', '', desc, '', '10', 'on', 'on']
  hst:template: productlist-main
